### ISSUE TITLE
Where is the code for temperature dataset?

### ISSUE THREAD

**Issue by hbzhang** [oliverguhr/transformer-time-series-prediction#10]
In the two examples code shown, it is only for sin data not for temperature data. 

Where is the code for temperature dataset?

Thanks

**Comment by oliverguhr** [comment]
Both examples are in the files, just uncomment it: 
https://github.com/oliverguhr/transformer-time-series-prediction/blob/master/transformer-singlestep.py#L98

**Comment by oliverguhr** [comment]
Feel free to reopen the issue if you have any questions.

**Comment by oliverguhr** [comment]
Feel free to reopen the issue if you have any questions.
