### ISSUE TITLE
new question!!

### ISSUE THREAD

**Issue by WIKI2020** [oliverguhr/transformer-time-series-prediction#11]
Hello, the current situation is input [1 * 100] - > target [1 * 100], but if it is a CSV table, such as:
                            
                         featuresA          featuresB          featuresC
2021/1/10           .........
2021/1/11                                    ........
2021/1/12                                                             ...........
    .......

So the input is BATCH * 3 * 100(3 features , 100timestep),how to change your code, thank you!

**Comment by oliverguhr** [comment]
Currently this code does not support multivariate predictions. You need to change the model in order to train a model on multiple features. PRs would be very welcome.

**Comment by RuifMaxx** [comment]
maybe you can rerfer to this one https://github.com/RuifMaxx/Multidimensional-time-series-with-transformer
