### ISSUE TITLE
New question regarding the multistep prediction strategy

### ISSUE THREAD

**Issue by rodgdutra** [oliverguhr/transformer-time-series-prediction#14]
I was reading and debugging the multi-step implementation to understand it better. I've come across an interesting thing, seams like the features and labels in the training and evaluation are the same. This behavior is correct ? I thought that in a multi step prediction problem the input features is delayed in relation to the wanted labels, this way we have a window of past behavior of the data and we are aiming to predict the future behavior of the data.

**Comment by rodgdutra** [comment]
One can observe this in the lines:
https://github.com/oliverguhr/transformer-time-series-prediction/blob/570d39bc0bbd61c823626ec9ca8bb5696c068187/transformer-multistep.py#L91-L92

**Comment by oliverguhr** [comment]
In this case, it is correct. Depending on the training mode, the loss is calculated over the output (prediction window) or the whole sequence:

https://github.com/oliverguhr/transformer-time-series-prediction/blob/570d39bc0bbd61c823626ec9ca8bb5696c068187/transformer-multistep.py#L177-L180

You can use this line to change the behaviour:

https://github.com/oliverguhr/transformer-time-series-prediction/blob/570d39bc0bbd61c823626ec9ca8bb5696c068187/transformer-multistep.py#L14

Depending on the task, it is sometimes beneficial to train the model, to also predict the correct value for the input features. You can also read a bit about this flag in this issue: https://github.com/oliverguhr/transformer-time-series-prediction/issues/6
