### ISSUE TITLE
How to add support for multiple feature in PositionalEncoding

### ISSUE THREAD

**Issue by Aroosa1** [oliverguhr/transformer-time-series-prediction#18]
Hi,
For now PositionalEncoding is only able to map one dimensional to encoder dimension. Please provide a efficient way to map multi-variate feature to the encoder dimension.
Thanks

**Comment by oliverguhr** [comment]
You can add a linear layer that projects your data to the embeddeding size. You might can even replace the positional encoding with this linear layer.
