### ISSUE TITLE
How to predict in multi-dimension 

### ISSUE THREAD

**Issue by xiaoerlaigeid** [oliverguhr/transformer-time-series-prediction#19]
Hello I want to know in this code the prediction is one dimension. But in my problem, the prediction is three-dimensions. I want to know how to modify this code.

**Comment by oliverguhr** [comment]
You can add a linear layer that projects your data to the embeddeding size. You might can even replace the positional encoding with this linear layer.

**Comment by oliverguhr** [comment]
You just need to modify this line:
https://github.com/oliverguhr/transformer-time-series-prediction/blob/570d39bc0bbd61c823626ec9ca8bb5696c068187/transformer-singlestep.py#L51
It reduces the models feature to one dimension, simply put in a two and you get two output dimensions.
