### ISSUE TITLE
Understand multistep transformer

### ISSUE THREAD

**Issue by hagianga21** [oliverguhr/transformer-time-series-prediction#20]
Hi thanks for your work, may I ask what this line is used for? It seems you made the dataset smaller?
`train_sequence = train_sequence[:-output_window]`

**Comment by Saitorz** [comment]
same question

**Comment by oliverguhr** [comment]
This way we can make sure that the last training slice gets a complete "output window" to calculate the loss.
Let's say your input is 100 steps and your want to predict 1 step. If you have 1001 timesteps you can create 10 training examples. However, if you only have 1000 timesteps of data you can only create 9 non-overlapping training examples.

**Comment by oliverguhr** [comment]
I am closing this now. Feel free to reopen it or ask if you have any questions.
