### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. 

### ISSUE THREAD

**Issue by cyning911** [oliverguhr/transformer-time-series-prediction#21]
127     seq_len = min(batch_size, len(source) - 1 - i)
    128     data = source[i:i+seq_len]
--> 129     input = torch.stack(torch.stack([item[0] for item in data]).chunk(input_window, 1)) # 1 is feature size
    130     target = torch.stack(torch.stack([item[1] for item in data]).chunk(input_window, 1))
    131     return input, target

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

which version is your torch? I use the newest version in colab, but  occurs an error .  please help me.

**Comment by oliverguhr** [comment]
This should work with the current pytroch version. Can you provide a colab notebook?
