### ISSUE TITLE
Multistep Tranformer Input Zeroed

### ISSUE THREAD

**Issue by ilijanikolov** [oliverguhr/transformer-time-series-prediction#24]
I was wondering why the input to the multistep transformer has zeroes of length of the output_window. Is there a reason why we can't do it in the same way as for the single step transformer, that is, instead of [0 1 2 3 4 0 0], we have [0 1 2 3 4] for the input and [2 3 4 5 6] for the labels instead of [0 1 2 3 4 5 6]?

**Comment by oliverguhr** [comment]
Hello @ilijanikolov,
are you referring to this [line](https://github.com/oliverguhr/transformer-time-series-prediction/blob/4e120f3f9b67482dd9a8ca88b49671881120d20f/transformer-multistep.py#L91)? 

This looks like a bug to me. The model should work without these zeros, just like the single step model.

**Comment by ilijanikolov** [comment]
Yes, exactly, that's what I was thinking. 

Thank you!
