### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by thylm** [oliverguhr/transformer-time-series-prediction#9]
can I export the output by csv file instead of png image?

**Comment by oliverguhr** [comment]
Yes you can! Just modify [this line](https://github.com/oliverguhr/transformer-time-series-prediction/blob/master/transformer-singlestep.py#L201) and write the result in a csv file.

**Comment by oliverguhr** [comment]
Close this issue for now. Feel free to reopen it if you have any questions.
